name: docker-cicd

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build-tags:
    # Build and push the image with the tag name
    uses: soulsbros/CICD-template/.github/workflows/docker-build.yml@c8da0c61a5864a433a06151b74c48cf4b37eebfe # 1.1.0
    if: github.ref_type == 'tag'
    with:
      image-name: steeven9/foodalyzer:${{ github.ref_name }}
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-branches:
    # Build all branches but push only in main
    uses: soulsbros/CICD-template/.github/workflows/docker-build.yml@c8da0c61a5864a433a06151b74c48cf4b37eebfe # 1.1.0
    if: github.ref_type == 'branch'
    with:
      image-name: steeven9/foodalyzer:latest
      push: ${{ github.ref_name == 'main' }}
      ping_webhook: ${{ github.ref_name == 'main' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
